export{default as Header} from './Header/Header'
export{default as Orders} from './Orders/Oders'
export{default as Dilivery} from './Delivery/Delivery'
export{default as HomeReferrals} from './Home_referrals/HomeReferrals'
export{default as Faq} from './FAQ/Faq'
export{default as Testimonials} from './Testimonials/Testimonials'
